### ISSUE TITLE
Conda-forge package is out of date

### ISSUE THREAD

**Issue by douglowe** [ecmwf/cdsapi#13]
Would it be possible to update the conda-forge cdsapi package? Currently it is version 0.1.4.
[https://github.com/conda-forge/cdsapi-feedstock](url)

I use conda for all my package management - having the latest version on conda-forge would be useful for me, so that I don't have to have two competing package managers.

**Comment by StephanSiemen** [comment]
Hi @douglowe, thanks for making us aware of this. The conda-forge package is now updated to be 0.2.7 as on PyPi.

**Comment by douglowe** [comment]
Great - thanks for sorting this out quickly for me.
