### ISSUE TITLE
Error: "'tuple' object is not callable" upon calling c.retrieve() method

### ISSUE THREAD

**Issue by Samgrocock** [ecmwf/cdsapi#15]
**cdsapi version:** 0.2.7

**.cdsapirc file format:**
url: https://cds.climate.copernicus.eu/api/v2
key: UID:KEY

Can't figure out what's going wrong, I've seen that others are also having the same issue but haven't been able to find the cause or a fix.

**Comment by Samgrocock** [comment]
This was due to me failing to include the UID in the "key" argument for the api.client() call, so that splitting the string by ":" didn't yield a tuple with 2 items (UID, key). I removed the arguments from the call and now the .cdsapirc file is used which has the correct UID:KEY format.

**Comment by gmt3141** [comment]
You must agree with the license terms of the Copernicus products in this page (after login):

https://cds.climate.copernicus.eu/cdsapp/#!/terms/licence-to-use-copernicus-products
