### ISSUE TITLE
Sending multiple requests

### ISSUE THREAD

**Issue by e5k** [ecmwf/cdsapi#17]
Hello all,
This is a question rather than issue, but is there a way to send requests into the queue (i.e. as from the website) from the python api?
Thank you!

**Comment by chloeprodhomme** [comment]
Yes I have the same question.

**Comment by e5k** [comment]
@chloeprodhomme That was useful for me: https://github.com/ecmwf/cdsapi/issues/2

**Comment by EddyCMWF** [comment]
Hi,

The cdsapi does not offer any means to submit more than one job at a time. If you want to parallelise your submissions you can do this via your own means, as @e5k suggested. However....

Your priority in the queue is calculated based on how many jobs you have currently submitted, therefore to ensure the best results you should submit one by one, or in small numbers. This is to ensure fair usage of our system by all users.

Also, submitting jobs to our queue in too large numbers, too quickly is often identified as suspicious activity and steps will be taken to limit any such users activity.

Many thanks,
Eddy
