### ISSUE TITLE
wait_until_complete=False is confusing

### ISSUE THREAD

**Issue by baudouinth** [ecmwf/cdsapi#30]
When I use `wait_until_complete=False`, I expect the api to launch a product request without waiting for it to be completed. However, when I use it, no new request appears in https://cds.climate.copernicus.eu/cdsapp#!/yourrequests. Could you explain to me what this parameter really does ?

**Comment by julietbravo** [comment]
For others running into the same issue (like I just did), this behavior seems to be related to the `delete` keyword. With `delete=False`, it works for me:

    cdsapi.Client(wait_until_complete=False, delete=False)

**Comment by EddyCMWF** [comment]
Hi,
By default, the cdsapi deletes successful requests from your history. This is to prevent the history becoming too large for users that submit many jobs. I believe that what you expereinced was that the job had completed and cleaned itself up before you had chance to see it. As @julietbravo , you can prevent the deletion of the record using the `delete=False` option, this way you can keep track of all your requests until they are cleaned from the central database.
Thanks,
Eddy
