### ISSUE TITLE
Convert IP addresses in URLs to domain names

### ISSUE THREAD

**Issue by pc1729** [ecmwf/cdsapi#32]
Our outgoing firewall rules are based on domain names but CDS download URLs have IP addresses.  It was straightforward to modifiy api.py to do the conversion.  Would it be possible to include that as a feature?

**Comment by EddyCMWF** [comment]
Hi @pc1729 ,
I believe this is no longer an issue and CDS download URLs should have fully clarified DNSs and not IP addresses
Thanks,
Eddy
