### ISSUE TITLE
Exception: Missing/incomplete configuration 

### ISSUE THREAD

**Issue by saptisunil** [ecmwf/cdsapi#37]
Exception                                 Traceback (most recent call last)
<ipython-input-15-1e5108857bf6> in <module>
      1 import cdsapi
      2 
----> 3 c = cdsapi.Client()
      4 
      5 c.retrieve(

~\anaconda3\lib\site-packages\cdsapi\api.py in __init__(self, url, key, quiet, debug, verify, timeout, progress, full_stack, delete, retry_max, sleep_max, wait_until_complete, info_callback, warning_callback, error_callback, debug_callback, metadata, forget, session)
    299 
    300         if url is None or key is None or key is None:
--> 301             raise Exception("Missing/incomplete configuration file: %s" % (dotrc))
    302 
    303         self.url = url

Exception: Missing/incomplete configuration file: C:\Users\HP/.cdsapirc

**Comment by saptisunil** [comment]
Can anyone help me with this issue???

**Comment by lgloege** [comment]
@saptisunil It looks like you need to add `url: https://cds.climate.copernicus.eu/api/v2` to your `.cdsapirc` file.

Here is how to set it up if this file doesn't exist. 
https://cds.climate.copernicus.eu/api-how-to

**Comment by EddyCMWF** [comment]
Hi,
Thanks providing the solution @lgloege 
Eddy

**Comment by MeHashemi** [comment]
@lgloege it doesn't work for me. the .cdsapirc is complete.

**Comment by zachHTF** [comment]
> @lgloege it doesn't work for me. the .cdsapirc is complete.

Just put the two lines of text from the .cdsapirc file arguments in the cdsapi.Client(url = "...", key = "...") function instead.

**Comment by drleo037** [comment]
> @saptisunil It looks like you need to add `url: https://cds.climate.copernicus.eu/api/v2` to your `.cdsapirc` file.
> 
> Here is how to set it up if this file doesn't exist. https://cds.climate.copernicus.eu/api-how-to

The URL looks to be changed to: https://cds.climate.copernicus.eu/how-to-api   :-/
