### ISSUE TITLE
Exception: Resource cams-global-reanalysis-eac4 not found

### ISSUE THREAD

**Issue by Rich2020** [ecmwf/cdsapi#43]
Trying to retrieve data via API results in an exception (see title).
The code used was generated by the CAMS UI located here: https://ads.atmosphere.copernicus.eu/cdsapp#!/dataset/cams-global-reanalysis-eac4?tab=form

Code generated:

```
import cdsapi

c = cdsapi.Client()

c.retrieve(
    'cams-global-reanalysis-eac4',
    {
        'variable': 'temperature',
        'pressure_level': '1',
        'model_level': '1',
        'date': '2003-01-01/2020-12-31',
        'time': [
            '00:00', '03:00', '06:00',
            '09:00', '12:00', '15:00',
            '18:00', '21:00',
        ],
        'format': 'grib',
    },
    'download.grib')
```

All terms/conditions accepted and .cdsapirc set according to instructions laid out here (for Mac): https://ads.atmosphere.copernicus.eu/api-how-to

**UPDATE**: that error is very misleading. The issue was that I need to use the ADS URL and key (rather than the CDS version), as provided here: https://ads.atmosphere.copernicus.eu/api-how-to

**Comment by alexbnlee** [comment]
Thanks so much. It solves my issues, too.

**Comment by yuzhangtu** [comment]
Thanks! This informataion is very helpful. 
The ADS url and key are needed in .cdsapirc file to access the cams-global-reanalysis data.
I also have a test on downloading the ERA5 file. Then it is necessary to update the URL and key to ADS.
