### ISSUE TITLE
Requesting Ocean and Atmosphere variables from ERA5-hourly as netcdf leads to ocean variables incorrectly represented on atmospheric grid.

### ISSUE THREAD

**Issue by sdat2** [ecmwf/cdsapi#57]
I submitted a request for a regional box that roughly corresponds to the gulf of Mexico, for several variables of interest over the period of development of Katrina.

The surface atmosphere variables are correctly gridded.

The surface ocean variables only fill the top left quarter of the grid.

It looks like the lower resolution ocean variables have been added to the higher resolution atmospheric grid.

![output](https://user-images.githubusercontent.com/30407294/170956996-4fa1193d-f822-49e9-a27a-0327d7d6e359.png)

Request:

```python
import cdsapi

c = cdsapi.Client()
c.retrieve(
        "reanalysis-era5-single-levels",
        {
            "product_type": "reanalysis",
            "format": "netcdf",
            "variable": [
                "10m_u_component_of_wind",
                "10m_v_component_of_wind",
                "2m_dewpoint_temperature",
                "2m_temperature",
                "mean_sea_level_pressure",
                "mean_wave_direction",
                "mean_wave_period",
                "sea_surface_temperature",
                "significant_height_of_combined_wind_waves_and_swell",
                "surface_pressure",
                "total_precipitation",
            ],
            "year": "2005",
            "month": "08",
            "day": [
                "20",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "30",
                "31",
            ],
            "time": [
                "00:00",
                "01:00",
                "02:00",
                "03:00",
                "04:00",
                "05:00",
                "06:00",
                "07:00",
                "08:00",
                "09:00",
                "10:00",
                "11:00",
                "12:00",
                "13:00",
                "14:00",
                "15:00",
                "16:00",
                "17:00",
                "18:00",
                "19:00",
                "20:00",
                "21:00",
                "22:00",
                "23:00",
            ],
            "area": [35, -100, 15, -80],
        },
        "katrina_era5.nc")

**Comment by EddyCMWF** [comment]
Hi @sdat2 ,
This is an issue relared to the data and not an issue with the cdsapi software so I recommend that you request help from the CDS user support channels:
https://cds.climate.copernicus.eu/cdsapp#!/usersupport
They will help you with queries regarding the availability, quality and coverage of data and issues regarding valid requests etc.
Many thanks,
Eddy

**Comment by sdat2** [comment]
Hi @EddyCMWF, Thanks a lot for getting back to me. As far as I can understand, the problem isn't with the data itself, but with the assumption made by cdsapi that both data outputs will be on the same lat lon grid; Shouldn't it be that the ocean components have their own coarser grid coords/dims in the output netcdf, rather than giving them incorrect coordinates and assuming the resolution is the same as the atmospheric outputs?

**Comment by sdat2** [comment]
Sometimes people get around this sort of issue by calling it lat1, lat2 and so on..., but I guess there might be a reason why this isn't possible.
