### ISSUE TITLE
Exception: Resource reanalysis-era5-complete not found

### ISSUE THREAD

**Issue by theweathermanda** [ecmwf/cdsapi#7]
I am trying to use cdsapi to download model level data for ERA5 and am receiving the error: 'Exception: Resource reanalysis-era5-complete not found'

I have modified the download script presented here (https://confluence.ecmwf.int/display/CKB/How+to+download+ERA5), so I am not sure what the issue is. My scripts work for other datasets (pressure level data, surface data).

**Comment by Bielorusse** [comment]
Hi all,

I have encountered the same issue with another product, and with the example from the cdsapi readme: "small test retrieve of ERA5 data".

Surely there must be something wrong in my method. Any hint? 

Here is the code that I am using:
```
import cdsapi
import yaml

with open(".cdsapirc", "r") as f:
    credentials = yaml.safe_load(f)

cdsapi_client = cdsapi.Client(url=credentials["url"], key=credentials["key"])

cdsapi_client.retrieve(
    "reanalysis-era5-pressure-levels",
    {
        "variable": "temperature",
        "pressure_level": "1000",
        "product_type": "reanalysis",
        "date": "2017-12-01/2017-12-31",
        "time": "12:00",
        "format": "grib",
    },
    "download.grib",
)
```

**Comment by milanavuckovic** [comment]
Hi,
I had similar issue when I started using both Climate data store and Atmospheric data store, and stored credential for both in the same .cdsapirc file. The easiest way (although not super safe) for me was to explicitly put my email and key in the code and not read it from the file.
Can this be your case guys?

@theweathermanda can you please provide sample of your code too so maybe someone can notice what may be wrong?

Also, Climate data store has a dedicated forum where questions and problems are much more likely to be picked up by other users or Copernicus user support. The forum has CDS API dedicated page: https://confluence.ecmwf.int/pages/viewpage.action?pageId=133257505

**Comment by Bielorusse** [comment]
Thanks for pointing out to the forum. I will have a look again as soon as I find some time and try your method @milanavuckovic 

By the way for my project I ended up using [GFS data](https://www.ncdc.noaa.gov/data-access/model-data/model-datasets/global-forcast-system-gfs). Downloading was made easy with the [Grib filter](https://nomads.ncep.noaa.gov/txt_descriptions/grib_filter_doc.shtml). I wrote a [small wrapper function](https://github.com/Bielorusse/duventchezmoi/blob/master/modules/download_gfs.py) in python.

**Comment by Bielorusse** [comment]
I just tried again and it worked. Didn't change anything on my side though !

**Comment by EddyCMWF** [comment]
Hi,
It looks like this was a temporary issue with one of the datasets, and @milanavuckovic has kindly indicated that the Copernicus user support forum is the best place to follow such issues.
Forum: https://confluence.ecmwf.int/pages/viewpage.action?pageId=133257505 

There are also several other user support channels listed on the CDS pages for other similar issues:
https://cds.climate.copernicus.eu/cdsapp#!/usersupport

Thanks,
Eddy
