### ISSUE TITLE
Where is the full API documentation?

### ISSUE THREAD

**Issue by rabernat** [ecmwf/cdsapi#9]
Sorry for the silly issue, but I couldn't find it on the web.

I am looking for the full API documentation for the CDS API. I would like to read about all the different options, the allowed values, etc. Apologies if this is obvious, but I couldn't figure it out.

Thanks for providing this package.

**Comment by julianocruz** [comment]
I'm also looking for full documentation for the same reason as @rabernat.
If there's no documentation (or complete one), could someone please tell us where to find the options that the keys can assume for the request?
I've been searching exhaustively for it, especially for interpolation options.

**Comment by b8raoult** [comment]
Please contact copernicus-support@ecmwf.int, they will be able to help you.

**Comment by julianocruz** [comment]
Thank you @b8raoult !!!

**Comment by matteodefelice** [comment]
Any update on the documentation? So, will it be released in the future?

**Comment by b8raoult** [comment]
Are you looking for the documentation of the REST protocol, or what should be given as data requests?

**Comment by matteodefelice** [comment]
I would just need the documentation of cdsapi methods and attributes.

**Comment by b8raoult** [comment]
The only documentation available is there: https://cds.climate.copernicus.eu/api-how-to. `cdsapi.Client().retrieve()` is currently the only method that is supported. If and when more methods are added, this documentation will be updated.

**Comment by b8raoult** [comment]
I forgot, to find out about the valid key/values, you need to search for a dataset in the CDS catalogue, click on the `Download data` tab, make a selection and then click on `Show API requests` at the bottom of the form.

**Comment by matteodefelice** [comment]
Any plans to publish a proper documentation for the library?

**Comment by aejiogu** [comment]
@matteodefelice I ran into the same issue as you, but fortunately it seems that the request page on CDS "Download data" page for whatever dataset you need can generate the code for the api request. Just click "Show API request" at the bottom of the page.

**Comment by matteodefelice** [comment]
That is not the problem. It would be normal to have documentation explaining the various options and keywords, for example how to activate debug messages, avoid HTTPS, etc.

**Comment by khufkens** [comment]
Endpoints for the CDS-beta, or any beta service are listed in the test routines of the `cadsapi` package which is sideloaded by this one. YMMV as not all of them seem valid.

https://github.com/ecmwf-projects/cads-api-client/blob/main/tests/test_10_processing.py

additional references to account specific endpoints are made here:
https://github.com/ecmwf-projects/cads-api-client/blob/main/cads_api_client/profile.py

but these seem not to function, or I haven't been able to get them to work (due to an different base url?)
